// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DRAWPAGE_H
#define UI_DRAWPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DrawPage
extern void ui_DrawPage_screen_init(void);
extern void ui_DrawPage_screen_destroy(void);
extern lv_obj_t * ui_DrawPage;
extern lv_obj_t * ui_PanelToolbar;
extern lv_obj_t * ui_PenBtn;
extern lv_obj_t * ui_CusrsorBtn;
extern lv_obj_t * ui_BushBtn;
extern lv_obj_t * ui_earseBtn;
extern lv_obj_t * ui_ColorBtn;
extern void ui_event_CanvasSeetingsBtn(lv_event_t * e);
extern lv_obj_t * ui_CanvasSeetingsBtn;
extern lv_obj_t * ui_ToolBarLabel;
extern void ui_event_ShapeBtn(lv_event_t * e);
extern lv_obj_t * ui_ShapeBtn;
extern lv_obj_t * ui_ScreenShotBtn;
extern lv_obj_t * ui_PenSizePenal;
extern lv_obj_t * ui_Pensize1;
extern lv_obj_t * ui_Pensize2;
extern lv_obj_t * ui_Pensize3;
extern lv_obj_t * ui_Pensize4;
extern lv_obj_t * ui_ColorPanel;
extern lv_obj_t * ui_Colorwheel;
extern lv_obj_t * ui_BlackBtn;
extern void ui_event_ShutDraw(lv_event_t * e);
extern lv_obj_t * ui_ShutDraw;
extern lv_obj_t * ui_CanvasSettingPanel;
extern void ui_event_CanvasX(lv_event_t * e);
extern lv_obj_t * ui_CanvasX;
extern void ui_event_CanvasY(lv_event_t * e);
extern lv_obj_t * ui_CanvasY;
extern lv_obj_t * ui_CnavsSizeLabel;
extern lv_obj_t * ui_CanvasDupLabel;
extern lv_obj_t * ui_CanvasBGbtn1;
extern lv_obj_t * ui_CanvasBGbtn2;
extern lv_obj_t * ui_CanvasBGbtn3;
extern lv_obj_t * ui_CanvasBGbtn4;
extern lv_obj_t * ui_BgSizeConfirmBtn;
extern lv_obj_t * ui_Label1;
extern void ui_event_BgSizeKey(lv_event_t * e);
extern lv_obj_t * ui_BgSizeKey;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_ShapePanel;
extern lv_obj_t * ui_LineBtn;
extern lv_obj_t * ui_TriangelBtn;
extern lv_obj_t * ui_CirculeBtn;
extern lv_obj_t * ui_RectangularBtn;
extern lv_obj_t * ui_HexagonBtn;
extern lv_obj_t * ui_StarBtn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

