// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_DrawPage = NULL;
lv_obj_t * ui_PanelToolbar = NULL;
lv_obj_t * ui_PenBtn = NULL;
lv_obj_t * ui_CusrsorBtn = NULL;
lv_obj_t * ui_BushBtn = NULL;
lv_obj_t * ui_earseBtn = NULL;
lv_obj_t * ui_ColorBtn = NULL;
lv_obj_t * ui_CanvasSeetingsBtn = NULL;
lv_obj_t * ui_ToolBarLabel = NULL;
lv_obj_t * ui_ShapeBtn = NULL;
lv_obj_t * ui_ScreenShotBtn = NULL;
lv_obj_t * ui_PenSizePenal = NULL;
lv_obj_t * ui_Pensize1 = NULL;
lv_obj_t * ui_Pensize2 = NULL;
lv_obj_t * ui_Pensize3 = NULL;
lv_obj_t * ui_Pensize4 = NULL;
lv_obj_t * ui_ColorPanel = NULL;
lv_obj_t * ui_Colorwheel = NULL;
lv_obj_t * ui_BlackBtn = NULL;
lv_obj_t * ui_ShutDraw = NULL;
lv_obj_t * ui_CanvasSettingPanel = NULL;
lv_obj_t * ui_CanvasX = NULL;
lv_obj_t * ui_CanvasY = NULL;
lv_obj_t * ui_CnavsSizeLabel = NULL;
lv_obj_t * ui_CanvasDupLabel = NULL;
lv_obj_t * ui_CanvasBGbtn1 = NULL;
lv_obj_t * ui_CanvasBGbtn2 = NULL;
lv_obj_t * ui_CanvasBGbtn3 = NULL;
lv_obj_t * ui_CanvasBGbtn4 = NULL;
lv_obj_t * ui_BgSizeConfirmBtn = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_BgSizeKey = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_ShapePanel = NULL;
lv_obj_t * ui_LineBtn = NULL;
lv_obj_t * ui_TriangelBtn = NULL;
lv_obj_t * ui_CirculeBtn = NULL;
lv_obj_t * ui_RectangularBtn = NULL;
lv_obj_t * ui_HexagonBtn = NULL;
lv_obj_t * ui_StarBtn = NULL;
// event funtions
void ui_event_CanvasSeetingsBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_CanvasSettingPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_CanvasSettingPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ShapeBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_ShapePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_ShapePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_ShutDraw(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainPage_screen_init);
    }
}

void ui_event_CanvasX(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_BgSizeKey,  ui_CanvasX);
        _ui_flag_modify(ui_BgSizeKey, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_CanvasY(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_BgSizeKey,  ui_CanvasY);
        _ui_flag_modify(ui_BgSizeKey, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_BgSizeKey(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_BgSizeKey, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_DrawPage_screen_init(void)
{
    ui_DrawPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DrawPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DrawPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_DrawPage, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_PanelToolbar = lv_obj_create(ui_DrawPage);
    lv_obj_set_width(ui_PanelToolbar, 90);
    lv_obj_set_height(ui_PanelToolbar, 589);
    lv_obj_set_x(ui_PanelToolbar, -460);
    lv_obj_set_y(ui_PanelToolbar, -1);
    lv_obj_set_align(ui_PanelToolbar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelToolbar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelToolbar, lv_color_hex(0xE2E5E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelToolbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PenBtn = lv_btn_create(ui_PanelToolbar);
    lv_obj_set_width(ui_PenBtn, 77);
    lv_obj_set_height(ui_PenBtn, 54);
    lv_obj_set_x(ui_PenBtn, 1);
    lv_obj_set_y(ui_PenBtn, -158);
    lv_obj_set_align(ui_PenBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PenBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PenBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PenBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PenBtn, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PenBtn, &ui_img_1716423352, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PenBtn, lv_color_hex(0x5260F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PenBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_PenBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_PenBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_CusrsorBtn = lv_btn_create(ui_PanelToolbar);
    lv_obj_set_width(ui_CusrsorBtn, 81);
    lv_obj_set_height(ui_CusrsorBtn, 54);
    lv_obj_set_x(ui_CusrsorBtn, 1);
    lv_obj_set_y(ui_CusrsorBtn, -223);
    lv_obj_set_align(ui_CusrsorBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CusrsorBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CusrsorBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CusrsorBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CusrsorBtn, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_CusrsorBtn, &ui_img_1966341745, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_CusrsorBtn, lv_color_hex(0xD1D1D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_CusrsorBtn, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CusrsorBtn, lv_color_hex(0x5260F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_CusrsorBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_CusrsorBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_CusrsorBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_BushBtn = lv_btn_create(ui_PanelToolbar);
    lv_obj_set_width(ui_BushBtn, 81);
    lv_obj_set_height(ui_BushBtn, 54);
    lv_obj_set_x(ui_BushBtn, 1);
    lv_obj_set_y(ui_BushBtn, -88);
    lv_obj_set_align(ui_BushBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BushBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BushBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BushBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BushBtn, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BushBtn, &ui_img_1313573954, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_BushBtn, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_BushBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BushBtn, lv_color_hex(0x5260F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BushBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_BushBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_BushBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_earseBtn = lv_btn_create(ui_PanelToolbar);
    lv_obj_set_width(ui_earseBtn, 81);
    lv_obj_set_height(ui_earseBtn, 54);
    lv_obj_set_x(ui_earseBtn, 1);
    lv_obj_set_y(ui_earseBtn, -21);
    lv_obj_set_align(ui_earseBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_earseBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_earseBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_earseBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_earseBtn, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_earseBtn, &ui_img_1453421446, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_earseBtn, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_earseBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_earseBtn, lv_color_hex(0x5260F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_earseBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_earseBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_earseBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ColorBtn = lv_btn_create(ui_PanelToolbar);
    lv_obj_set_width(ui_ColorBtn, 77);
    lv_obj_set_height(ui_ColorBtn, 54);
    lv_obj_set_x(ui_ColorBtn, 1);
    lv_obj_set_y(ui_ColorBtn, 47);
    lv_obj_set_align(ui_ColorBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ColorBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ColorBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ColorBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ColorBtn, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ColorBtn, &ui_img_1028212308, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ColorBtn, lv_color_hex(0x5260F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ColorBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_ColorBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_ColorBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_CanvasSeetingsBtn = lv_btn_create(ui_PanelToolbar);
    lv_obj_set_width(ui_CanvasSeetingsBtn, 77);
    lv_obj_set_height(ui_CanvasSeetingsBtn, 54);
    lv_obj_set_x(ui_CanvasSeetingsBtn, 1);
    lv_obj_set_y(ui_CanvasSeetingsBtn, 115);
    lv_obj_set_align(ui_CanvasSeetingsBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CanvasSeetingsBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CanvasSeetingsBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CanvasSeetingsBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CanvasSeetingsBtn, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_CanvasSeetingsBtn, &ui_img_578315105, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_CanvasSeetingsBtn, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_CanvasSeetingsBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CanvasSeetingsBtn, lv_color_hex(0x5260F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_CanvasSeetingsBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_CanvasSeetingsBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_CanvasSeetingsBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ToolBarLabel = lv_label_create(ui_PanelToolbar);
    lv_obj_set_width(ui_ToolBarLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ToolBarLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ToolBarLabel, -3);
    lv_obj_set_y(ui_ToolBarLabel, -269);
    lv_obj_set_align(ui_ToolBarLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ToolBarLabel, "Tool");
    lv_obj_set_style_text_color(ui_ToolBarLabel, lv_color_hex(0x3B3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ToolBarLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ToolBarLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShapeBtn = lv_btn_create(ui_PanelToolbar);
    lv_obj_set_width(ui_ShapeBtn, 77);
    lv_obj_set_height(ui_ShapeBtn, 54);
    lv_obj_set_x(ui_ShapeBtn, 1);
    lv_obj_set_y(ui_ShapeBtn, 184);
    lv_obj_set_align(ui_ShapeBtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ShapeBtn, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ShapeBtn, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_ShapeBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ShapeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ShapeBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShapeBtn, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ShapeBtn, &ui_img_929597880, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ShapeBtn, lv_color_hex(0x737378), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ShapeBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ShapeBtn, lv_color_hex(0x5260F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ShapeBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_ShapeBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_ShapeBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ScreenShotBtn = lv_btn_create(ui_PanelToolbar);
    lv_obj_set_width(ui_ScreenShotBtn, 77);
    lv_obj_set_height(ui_ScreenShotBtn, 54);
    lv_obj_set_x(ui_ScreenShotBtn, 0);
    lv_obj_set_y(ui_ScreenShotBtn, 253);
    lv_obj_set_align(ui_ScreenShotBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenShotBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScreenShotBtn, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenShotBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenShotBtn, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ScreenShotBtn, &ui_img_895563273, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ScreenShotBtn, lv_color_hex(0x6A6B70), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ScreenShotBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenShotBtn, lv_color_hex(0x5260F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ScreenShotBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_ScreenShotBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_ScreenShotBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_ScreenShotBtn, lv_color_hex(0x5260F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ScreenShotBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_ScreenShotBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_ScreenShotBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_PenSizePenal = lv_obj_create(ui_DrawPage);
    lv_obj_set_width(ui_PenSizePenal, 100);
    lv_obj_set_height(ui_PenSizePenal, 159);
    lv_obj_set_x(ui_PenSizePenal, -363);
    lv_obj_set_y(ui_PenSizePenal, -128);
    lv_obj_set_align(ui_PenSizePenal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PenSizePenal, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PenSizePenal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PenSizePenal, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pensize1 = lv_btn_create(ui_PenSizePenal);
    lv_obj_set_width(ui_Pensize1, 88);
    lv_obj_set_height(ui_Pensize1, 30);
    lv_obj_set_x(ui_Pensize1, -1);
    lv_obj_set_y(ui_Pensize1, -52);
    lv_obj_set_align(ui_Pensize1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pensize1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pensize1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Pensize1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pensize1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Pensize1, &ui_img_28177221, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Pensize1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Pensize1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Pensize1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pensize1, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Pensize1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Pensize2 = lv_btn_create(ui_PenSizePenal);
    lv_obj_set_width(ui_Pensize2, 88);
    lv_obj_set_height(ui_Pensize2, 30);
    lv_obj_set_x(ui_Pensize2, -1);
    lv_obj_set_y(ui_Pensize2, -18);
    lv_obj_set_align(ui_Pensize2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pensize2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pensize2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Pensize2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pensize2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Pensize2, &ui_img_1053551958, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Pensize2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Pensize2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pensize2, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Pensize2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Pensize3 = lv_btn_create(ui_PenSizePenal);
    lv_obj_set_width(ui_Pensize3, 88);
    lv_obj_set_height(ui_Pensize3, 30);
    lv_obj_set_x(ui_Pensize3, -1);
    lv_obj_set_y(ui_Pensize3, 15);
    lv_obj_set_align(ui_Pensize3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pensize3, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pensize3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Pensize3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pensize3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Pensize3, &ui_img_381824271, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Pensize3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Pensize3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pensize3, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Pensize3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Pensize4 = lv_btn_create(ui_PenSizePenal);
    lv_obj_set_width(ui_Pensize4, 88);
    lv_obj_set_height(ui_Pensize4, 30);
    lv_obj_set_x(ui_Pensize4, -1);
    lv_obj_set_y(ui_Pensize4, 50);
    lv_obj_set_align(ui_Pensize4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pensize4, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pensize4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Pensize4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pensize4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Pensize4, &ui_img_699904908, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Pensize4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Pensize4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pensize4, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Pensize4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ColorPanel = lv_obj_create(ui_DrawPage);
    lv_obj_set_width(ui_ColorPanel, 165);
    lv_obj_set_height(ui_ColorPanel, 174);
    lv_obj_set_x(ui_ColorPanel, -320);
    lv_obj_set_y(ui_ColorPanel, 110);
    lv_obj_set_align(ui_ColorPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ColorPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ColorPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ColorPanel, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ColorPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ColorPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Colorwheel = lv_colorwheel_create(ui_ColorPanel, true);
    lv_obj_set_width(ui_Colorwheel, 136);
    lv_obj_set_height(ui_Colorwheel, 136);
    lv_obj_set_x(ui_Colorwheel, -3);
    lv_obj_set_y(ui_Colorwheel, -7);
    lv_obj_set_align(ui_Colorwheel, LV_ALIGN_CENTER);

    ui_BlackBtn = lv_btn_create(ui_ColorPanel);
    lv_obj_set_width(ui_BlackBtn, 34);
    lv_obj_set_height(ui_BlackBtn, 32);
    lv_obj_set_x(ui_BlackBtn, -3);
    lv_obj_set_y(ui_BlackBtn, -12);
    lv_obj_set_align(ui_BlackBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BlackBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BlackBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BlackBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BlackBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BlackBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShutDraw = lv_btn_create(ui_DrawPage);
    lv_obj_set_width(ui_ShutDraw, 47);
    lv_obj_set_height(ui_ShutDraw, 50);
    lv_obj_set_x(ui_ShutDraw, 467);
    lv_obj_set_y(ui_ShutDraw, -258);
    lv_obj_set_align(ui_ShutDraw, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ShutDraw, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ShutDraw, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ShutDraw, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ShutDraw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShutDraw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ShutDraw, &ui_img_1950574165, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ShutDraw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ShutDraw, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ShutDraw, lv_color_hex(0xD3CCCC), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ShutDraw, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_ShutDraw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_ShutDraw, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_CanvasSettingPanel = lv_obj_create(ui_DrawPage);
    lv_obj_set_width(ui_CanvasSettingPanel, 286);
    lv_obj_set_height(ui_CanvasSettingPanel, 159);
    lv_obj_set_x(ui_CanvasSettingPanel, -260);
    lv_obj_set_y(ui_CanvasSettingPanel, 173);
    lv_obj_set_align(ui_CanvasSettingPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CanvasSettingPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_CanvasSettingPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CanvasSettingPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CanvasX = lv_textarea_create(ui_CanvasSettingPanel);
    lv_obj_set_width(ui_CanvasX, 57);
    lv_obj_set_height(ui_CanvasX, LV_SIZE_CONTENT);    /// 38
    lv_obj_set_x(ui_CanvasX, -48);
    lv_obj_set_y(ui_CanvasX, -38);
    lv_obj_set_align(ui_CanvasX, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_CanvasX, "1024");
    lv_textarea_set_one_line(ui_CanvasX, true);

    ui_CanvasY = lv_textarea_create(ui_CanvasSettingPanel);
    lv_obj_set_width(ui_CanvasY, 53);
    lv_obj_set_height(ui_CanvasY, LV_SIZE_CONTENT);    /// 38
    lv_obj_set_x(ui_CanvasY, 36);
    lv_obj_set_y(ui_CanvasY, -40);
    lv_obj_set_align(ui_CanvasY, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_CanvasY, "600");
    lv_textarea_set_one_line(ui_CanvasY, true);

    ui_CnavsSizeLabel = lv_label_create(ui_CanvasSettingPanel);
    lv_obj_set_width(ui_CnavsSizeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CnavsSizeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CnavsSizeLabel, -108);
    lv_obj_set_y(ui_CnavsSizeLabel, -39);
    lv_obj_set_align(ui_CnavsSizeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CnavsSizeLabel, "Size:");
    lv_obj_set_style_text_font(ui_CnavsSizeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CanvasDupLabel = lv_label_create(ui_CanvasSettingPanel);
    lv_obj_set_width(ui_CanvasDupLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CanvasDupLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CanvasDupLabel, -4);
    lv_obj_set_y(ui_CanvasDupLabel, -36);
    lv_obj_set_align(ui_CanvasDupLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CanvasDupLabel, "x");

    ui_CanvasBGbtn1 = lv_btn_create(ui_CanvasSettingPanel);
    lv_obj_set_width(ui_CanvasBGbtn1, 50);
    lv_obj_set_height(ui_CanvasBGbtn1, 50);
    lv_obj_set_x(ui_CanvasBGbtn1, -102);
    lv_obj_set_y(ui_CanvasBGbtn1, 33);
    lv_obj_set_align(ui_CanvasBGbtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CanvasBGbtn1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CanvasBGbtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CanvasBGbtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CanvasBGbtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_CanvasBGbtn1, &ui_img_canvas1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_CanvasBGbtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_CanvasBGbtn1, lv_color_hex(0xDBE1E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_CanvasBGbtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_CanvasBGbtn1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_CanvasBGbtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CanvasBGbtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_CanvasBGbtn1, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_CanvasBGbtn1, lv_color_hex(0x8685FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_CanvasBGbtn1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_CanvasBGbtn1, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_CanvasBGbtn1, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_CanvasBGbtn2 = lv_btn_create(ui_CanvasSettingPanel);
    lv_obj_set_width(ui_CanvasBGbtn2, 50);
    lv_obj_set_height(ui_CanvasBGbtn2, 50);
    lv_obj_set_x(ui_CanvasBGbtn2, -29);
    lv_obj_set_y(ui_CanvasBGbtn2, 33);
    lv_obj_set_align(ui_CanvasBGbtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CanvasBGbtn2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CanvasBGbtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_CanvasBGbtn2, &ui_img_canvas1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_CanvasBGbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_CanvasBGbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_CanvasBGbtn2, lv_color_hex(0x8685FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_CanvasBGbtn2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_CanvasBGbtn2, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_CanvasBGbtn2, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_CanvasBGbtn3 = lv_btn_create(ui_CanvasSettingPanel);
    lv_obj_set_width(ui_CanvasBGbtn3, 50);
    lv_obj_set_height(ui_CanvasBGbtn3, 50);
    lv_obj_set_x(ui_CanvasBGbtn3, 37);
    lv_obj_set_y(ui_CanvasBGbtn3, 33);
    lv_obj_set_align(ui_CanvasBGbtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CanvasBGbtn3, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CanvasBGbtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_CanvasBGbtn3, &ui_img_canvas2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_CanvasBGbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_CanvasBGbtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_CanvasBGbtn3, lv_color_hex(0x8685FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_CanvasBGbtn3, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_CanvasBGbtn3, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_CanvasBGbtn3, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_CanvasBGbtn4 = lv_btn_create(ui_CanvasSettingPanel);
    lv_obj_set_width(ui_CanvasBGbtn4, 50);
    lv_obj_set_height(ui_CanvasBGbtn4, 50);
    lv_obj_set_x(ui_CanvasBGbtn4, 102);
    lv_obj_set_y(ui_CanvasBGbtn4, 32);
    lv_obj_set_align(ui_CanvasBGbtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CanvasBGbtn4, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CanvasBGbtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_CanvasBGbtn4, &ui_img_canvas3_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_CanvasBGbtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_CanvasBGbtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_CanvasBGbtn4, lv_color_hex(0x8685FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_CanvasBGbtn4, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_CanvasBGbtn4, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_CanvasBGbtn4, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_BgSizeConfirmBtn = lv_btn_create(ui_CanvasSettingPanel);
    lv_obj_set_width(ui_BgSizeConfirmBtn, 58);
    lv_obj_set_height(ui_BgSizeConfirmBtn, 36);
    lv_obj_set_x(ui_BgSizeConfirmBtn, 103);
    lv_obj_set_y(ui_BgSizeConfirmBtn, -38);
    lv_obj_set_align(ui_BgSizeConfirmBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BgSizeConfirmBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BgSizeConfirmBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BgSizeConfirmBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BgSizeConfirmBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BgSizeConfirmBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BgSizeConfirmBtn, lv_color_hex(0xDBE0E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BgSizeConfirmBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BgSizeConfirmBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BgSizeConfirmBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BgSizeConfirmBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BgSizeConfirmBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BgSizeConfirmBtn, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BgSizeConfirmBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label1 = lv_label_create(ui_BgSizeConfirmBtn);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 1);
    lv_obj_set_y(ui_Label1, -1);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "confirm");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BgSizeKey = lv_keyboard_create(ui_DrawPage);
    lv_obj_set_width(ui_BgSizeKey, 662);
    lv_obj_set_height(ui_BgSizeKey, 252);
    lv_obj_set_x(ui_BgSizeKey, 177);
    lv_obj_set_y(ui_BgSizeKey, 173);
    lv_obj_set_align(ui_BgSizeKey, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BgSizeKey, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Image1 = lv_img_create(ui_DrawPage);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 114);
    lv_obj_set_y(ui_Image1, -139);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Image1, &ui_img_canvasbg1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_DrawPage);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 253);
    lv_obj_set_y(ui_Image2, -23);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Image2, &ui_img_canvasbg2_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_DrawPage);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Image3, &ui_img_canvasbg3_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShapePanel = lv_obj_create(ui_DrawPage);
    lv_obj_set_width(ui_ShapePanel, 156);
    lv_obj_set_height(ui_ShapePanel, 115);
    lv_obj_set_x(ui_ShapePanel, -328);
    lv_obj_set_y(ui_ShapePanel, 207);
    lv_obj_set_align(ui_ShapePanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ShapePanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ShapePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ShapePanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LineBtn = lv_btn_create(ui_ShapePanel);
    lv_obj_set_width(ui_LineBtn, 40);
    lv_obj_set_height(ui_LineBtn, 40);
    lv_obj_set_x(ui_LineBtn, -48);
    lv_obj_set_y(ui_LineBtn, -28);
    lv_obj_set_align(ui_LineBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LineBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LineBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LineBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LineBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_LineBtn, &ui_img_1479983256, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LineBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LineBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LineBtn, lv_color_hex(0xC6C6CC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_LineBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TriangelBtn = lv_btn_create(ui_ShapePanel);
    lv_obj_set_width(ui_TriangelBtn, 40);
    lv_obj_set_height(ui_TriangelBtn, 40);
    lv_obj_set_x(ui_TriangelBtn, -3);
    lv_obj_set_y(ui_TriangelBtn, -28);
    lv_obj_set_align(ui_TriangelBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TriangelBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TriangelBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TriangelBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TriangelBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_TriangelBtn, &ui_img_2132644374, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TriangelBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TriangelBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TriangelBtn, lv_color_hex(0xC6C6CC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_TriangelBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_CirculeBtn = lv_btn_create(ui_ShapePanel);
    lv_obj_set_width(ui_CirculeBtn, 40);
    lv_obj_set_height(ui_CirculeBtn, 40);
    lv_obj_set_x(ui_CirculeBtn, 45);
    lv_obj_set_y(ui_CirculeBtn, -28);
    lv_obj_set_align(ui_CirculeBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CirculeBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CirculeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CirculeBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CirculeBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_CirculeBtn, &ui_img_1668448959, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_CirculeBtn, lv_color_hex(0x353535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_CirculeBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_CirculeBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_CirculeBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CirculeBtn, lv_color_hex(0xC6C6CC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_CirculeBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_RectangularBtn = lv_btn_create(ui_ShapePanel);
    lv_obj_set_width(ui_RectangularBtn, 40);
    lv_obj_set_height(ui_RectangularBtn, 40);
    lv_obj_set_x(ui_RectangularBtn, -48);
    lv_obj_set_y(ui_RectangularBtn, 27);
    lv_obj_set_align(ui_RectangularBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RectangularBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RectangularBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RectangularBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RectangularBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_RectangularBtn, &ui_img_1279319559, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_RectangularBtn, lv_color_hex(0x262627), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_RectangularBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RectangularBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RectangularBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RectangularBtn, lv_color_hex(0xC6C6CC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_RectangularBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_HexagonBtn = lv_btn_create(ui_ShapePanel);
    lv_obj_set_width(ui_HexagonBtn, 40);
    lv_obj_set_height(ui_HexagonBtn, 40);
    lv_obj_set_x(ui_HexagonBtn, -3);
    lv_obj_set_y(ui_HexagonBtn, 27);
    lv_obj_set_align(ui_HexagonBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HexagonBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HexagonBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HexagonBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HexagonBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_HexagonBtn, &ui_img_258598861, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_HexagonBtn, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_HexagonBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_HexagonBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_HexagonBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HexagonBtn, lv_color_hex(0xC6C6CC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_HexagonBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_StarBtn = lv_btn_create(ui_ShapePanel);
    lv_obj_set_width(ui_StarBtn, 40);
    lv_obj_set_height(ui_StarBtn, 40);
    lv_obj_set_x(ui_StarBtn, 45);
    lv_obj_set_y(ui_StarBtn, 27);
    lv_obj_set_align(ui_StarBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StarBtn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StarBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StarBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StarBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_StarBtn, &ui_img_1527121588, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_StarBtn, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_StarBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_StarBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_StarBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StarBtn, lv_color_hex(0xC6C6CC), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_StarBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_CanvasSeetingsBtn, ui_event_CanvasSeetingsBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ShapeBtn, ui_event_ShapeBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ShutDraw, ui_event_ShutDraw, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CanvasX, ui_event_CanvasX, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CanvasY, ui_event_CanvasY, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BgSizeKey, ui_event_BgSizeKey, LV_EVENT_ALL, NULL);

}

void ui_DrawPage_screen_destroy(void)
{
    if(ui_DrawPage) lv_obj_del(ui_DrawPage);

    // NULL screen variables
    ui_DrawPage = NULL;
    ui_PanelToolbar = NULL;
    ui_PenBtn = NULL;
    ui_CusrsorBtn = NULL;
    ui_BushBtn = NULL;
    ui_earseBtn = NULL;
    ui_ColorBtn = NULL;
    ui_CanvasSeetingsBtn = NULL;
    ui_ToolBarLabel = NULL;
    ui_ShapeBtn = NULL;
    ui_ScreenShotBtn = NULL;
    ui_PenSizePenal = NULL;
    ui_Pensize1 = NULL;
    ui_Pensize2 = NULL;
    ui_Pensize3 = NULL;
    ui_Pensize4 = NULL;
    ui_ColorPanel = NULL;
    ui_Colorwheel = NULL;
    ui_BlackBtn = NULL;
    ui_ShutDraw = NULL;
    ui_CanvasSettingPanel = NULL;
    ui_CanvasX = NULL;
    ui_CanvasY = NULL;
    ui_CnavsSizeLabel = NULL;
    ui_CanvasDupLabel = NULL;
    ui_CanvasBGbtn1 = NULL;
    ui_CanvasBGbtn2 = NULL;
    ui_CanvasBGbtn3 = NULL;
    ui_CanvasBGbtn4 = NULL;
    ui_BgSizeConfirmBtn = NULL;
    ui_Label1 = NULL;
    ui_BgSizeKey = NULL;
    ui_Image1 = NULL;
    ui_Image2 = NULL;
    ui_Image3 = NULL;
    ui_ShapePanel = NULL;
    ui_LineBtn = NULL;
    ui_TriangelBtn = NULL;
    ui_CirculeBtn = NULL;
    ui_RectangularBtn = NULL;
    ui_HexagonBtn = NULL;
    ui_StarBtn = NULL;

}
