// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_FilePage = NULL;
lv_obj_t * ui_ShutDraw2 = NULL;
lv_obj_t * ui_myscreenshotPanel = NULL;
lv_obj_t * ui_prevBtn = NULL;
lv_obj_t * ui_NextBtn = NULL;
lv_obj_t * ui_photoShow = NULL;
lv_obj_t * ui_DeleteBtn = NULL;
lv_obj_t * ui_photoLib = NULL;
lv_obj_t * ui_myscreenLabel = NULL;
// event funtions
void ui_event_ShutDraw2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainPage_screen_init);
    }
}

// build funtions

void ui_FilePage_screen_init(void)
{
    ui_FilePage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FilePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ShutDraw2 = lv_btn_create(ui_FilePage);
    lv_obj_set_width(ui_ShutDraw2, 47);
    lv_obj_set_height(ui_ShutDraw2, 50);
    lv_obj_set_x(ui_ShutDraw2, 446);
    lv_obj_set_y(ui_ShutDraw2, -244);
    lv_obj_set_align(ui_ShutDraw2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ShutDraw2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ShutDraw2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ShutDraw2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ShutDraw2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShutDraw2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ShutDraw2, &ui_img_1950574165, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ShutDraw2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ShutDraw2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ShutDraw2, lv_color_hex(0xD3CCCC), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ShutDraw2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_ShutDraw2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_ShutDraw2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_myscreenshotPanel = lv_obj_create(ui_FilePage);
    lv_obj_set_width(ui_myscreenshotPanel, 755);
    lv_obj_set_height(ui_myscreenshotPanel, 433);
    lv_obj_set_x(ui_myscreenshotPanel, 119);
    lv_obj_set_y(ui_myscreenshotPanel, 14);
    lv_obj_set_align(ui_myscreenshotPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_myscreenshotPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_myscreenshotPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_myscreenshotPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_myscreenshotPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_myscreenshotPanel, lv_color_hex(0xDCDCDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_myscreenshotPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_prevBtn = lv_btn_create(ui_FilePage);
    lv_obj_set_width(ui_prevBtn, 58);
    lv_obj_set_height(ui_prevBtn, 50);
    lv_obj_set_x(ui_prevBtn, -450);
    lv_obj_set_y(ui_prevBtn, 184);
    lv_obj_set_align(ui_prevBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_prevBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_prevBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_prevBtn, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_prevBtn, lv_color_hex(0xBABABA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_prevBtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_prevBtn, &ui_img_1073906465, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_prevBtn, lv_color_hex(0x474CFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_prevBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_prevBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_prevBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_NextBtn = lv_btn_create(ui_FilePage);
    lv_obj_set_width(ui_NextBtn, 58);
    lv_obj_set_height(ui_NextBtn, 50);
    lv_obj_set_x(ui_NextBtn, -326);
    lv_obj_set_y(ui_NextBtn, 184);
    lv_obj_set_align(ui_NextBtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_NextBtn, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_NextBtn, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_NextBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NextBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NextBtn, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NextBtn, lv_color_hex(0xBABABA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NextBtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_NextBtn, &ui_img_299028513, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NextBtn, lv_color_hex(0x474CFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_NextBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_NextBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_NextBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_photoShow = lv_img_create(ui_FilePage);
    lv_obj_set_width(ui_photoShow, LV_SIZE_CONTENT);   /// 720
    lv_obj_set_height(ui_photoShow, LV_SIZE_CONTENT);    /// 395
    lv_obj_set_x(ui_photoShow, 96);
    lv_obj_set_y(ui_photoShow, 6);
    lv_obj_set_align(ui_photoShow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_photoShow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_photoShow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_photoShow, lv_color_hex(0x8C8C8C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_photoShow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_photoShow, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeleteBtn = lv_btn_create(ui_FilePage);
    lv_obj_set_width(ui_DeleteBtn, 58);
    lv_obj_set_height(ui_DeleteBtn, 50);
    lv_obj_set_x(ui_DeleteBtn, 447);
    lv_obj_set_y(ui_DeleteBtn, 182);
    lv_obj_set_align(ui_DeleteBtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DeleteBtn, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_DeleteBtn, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_DeleteBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DeleteBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DeleteBtn, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DeleteBtn, lv_color_hex(0x535353), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeleteBtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_DeleteBtn, &ui_img_537269857, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DeleteBtn, lv_color_hex(0x474CFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_DeleteBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_DeleteBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_DeleteBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_photoLib = lv_roller_create(ui_FilePage);
    lv_roller_set_options(ui_photoLib, "AAAAAAAAAAAAAAAAAA\np2\np3\np4", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_photoLib, 170);
    lv_obj_set_width(ui_photoLib, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_photoLib, -387);
    lv_obj_set_y(ui_photoLib, -23);
    lv_obj_set_align(ui_photoLib, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_photoLib, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myscreenLabel = lv_label_create(ui_FilePage);
    lv_obj_set_width(ui_myscreenLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myscreenLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_myscreenLabel, -390);
    lv_obj_set_y(ui_myscreenLabel, -233);
    lv_obj_set_align(ui_myscreenLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_myscreenLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_myscreenLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_myscreenLabel, "MY SCREENSHOT");
    lv_obj_set_style_text_font(ui_myscreenLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ShutDraw2, ui_event_ShutDraw2, LV_EVENT_ALL, NULL);

}

void ui_FilePage_screen_destroy(void)
{
    if(ui_FilePage) lv_obj_del(ui_FilePage);

    // NULL screen variables
    ui_FilePage = NULL;
    ui_ShutDraw2 = NULL;
    ui_myscreenshotPanel = NULL;
    ui_prevBtn = NULL;
    ui_NextBtn = NULL;
    ui_photoShow = NULL;
    ui_DeleteBtn = NULL;
    ui_photoLib = NULL;
    ui_myscreenLabel = NULL;

}
