// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_FILEPAGE_H
#define UI_FILEPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_FilePage
extern void ui_FilePage_screen_init(void);
extern void ui_FilePage_screen_destroy(void);
extern lv_obj_t * ui_FilePage;
extern void ui_event_ShutDraw2(lv_event_t * e);
extern lv_obj_t * ui_ShutDraw2;
extern lv_obj_t * ui_myscreenshotPanel;
extern lv_obj_t * ui_prevBtn;
extern lv_obj_t * ui_NextBtn;
extern lv_obj_t * ui_photoShow;
extern lv_obj_t * ui_DeleteBtn;
extern lv_obj_t * ui_photoLib;
extern lv_obj_t * ui_myscreenLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

