// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LOGINPAGE_H
#define UI_LOGINPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LoginPage
extern void ui_LoginPage_screen_init(void);
extern void ui_LoginPage_screen_destroy(void);
extern lv_obj_t * ui_LoginPage;
extern lv_obj_t * ui_pdText;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_RTab;
extern lv_obj_t * ui_Register;
extern lv_obj_t * ui_RegisterLabel;
extern void ui_event_Raccount(lv_event_t * e);
extern lv_obj_t * ui_Raccount;
extern void ui_event_Rpassword(lv_event_t * e);
extern lv_obj_t * ui_Rpassword;
extern void ui_event_RpeatePassword(lv_event_t * e);
extern lv_obj_t * ui_RpeatePassword;
extern lv_obj_t * ui_LTab;
extern void ui_event_accountText(lv_event_t * e);
extern lv_obj_t * ui_accountText;
extern void ui_event_paswdtext(lv_event_t * e);
extern lv_obj_t * ui_paswdtext;
extern lv_obj_t * ui_Login;
extern lv_obj_t * ui_Loginabel;
extern lv_obj_t * ui_WelcomeLabel;
extern void ui_event_LoginKeyboard(lv_event_t * e);
extern lv_obj_t * ui_LoginKeyboard;
extern lv_obj_t * ui_loginmessPanel;
extern lv_obj_t * ui_loginmessLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

