// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_LoginPage = NULL;
lv_obj_t * ui_pdText = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_RTab = NULL;
lv_obj_t * ui_Register = NULL;
lv_obj_t * ui_RegisterLabel = NULL;
lv_obj_t * ui_Raccount = NULL;
lv_obj_t * ui_Rpassword = NULL;
lv_obj_t * ui_RpeatePassword = NULL;
lv_obj_t * ui_LTab = NULL;
lv_obj_t * ui_accountText = NULL;
lv_obj_t * ui_paswdtext = NULL;
lv_obj_t * ui_Login = NULL;
lv_obj_t * ui_Loginabel = NULL;
lv_obj_t * ui_WelcomeLabel = NULL;
lv_obj_t * ui_LoginKeyboard = NULL;
lv_obj_t * ui_loginmessPanel = NULL;
lv_obj_t * ui_loginmessLabel = NULL;
// event funtions
void ui_event_Raccount(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_LoginKeyboard,  ui_Raccount);
        _ui_flag_modify(ui_LoginKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Rpassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_LoginKeyboard,  ui_Rpassword);
        _ui_flag_modify(ui_LoginKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_RpeatePassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_LoginKeyboard,  ui_RpeatePassword);
        _ui_flag_modify(ui_LoginKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_accountText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_LoginKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_LoginKeyboard,  ui_accountText);
    }
}

void ui_event_paswdtext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_LoginKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_LoginKeyboard,  ui_paswdtext);
    }
}

void ui_event_LoginKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_LoginKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_LoginPage_screen_init(void)
{
    ui_LoginPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LoginPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LoginPage, lv_color_hex(0xEBEBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoginPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pdText = lv_obj_create(ui_LoginPage);
    lv_obj_set_width(ui_pdText, 479);
    lv_obj_set_height(ui_pdText, 573);
    lv_obj_set_x(ui_pdText, 16);
    lv_obj_set_y(ui_pdText, 2);
    lv_obj_set_align(ui_pdText, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pdText, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pdText, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pdText, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pdText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pdText, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pdText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_pdText, LV_DIR_TOP, 55);
    lv_obj_set_width(ui_TabView1, 388);
    lv_obj_set_height(ui_TabView1, 469);
    lv_obj_set_x(ui_TabView1, 2);
    lv_obj_set_y(ui_TabView1, 23);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TabView1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_TabView1, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_tabview_get_tab_btns(ui_TabView1), 50,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x020202),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView1), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(lv_tabview_get_tab_btns(ui_TabView1), &ui_img_whitebtn_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(lv_tabview_get_tab_btns(ui_TabView1), 20,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0xC6C6C6),
                              LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x000000),
                                  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_TabView1), 0,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x000000),
                                LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0xFFFFFF),
                              LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);

    ui_RTab = lv_tabview_add_tab(ui_TabView1, "Register");
    lv_obj_add_state(ui_RTab, LV_STATE_CHECKED);       /// States

    ui_Register = lv_btn_create(ui_RTab);
    lv_obj_set_width(ui_Register, 230);
    lv_obj_set_height(ui_Register, 50);
    lv_obj_set_x(ui_Register, -4);
    lv_obj_set_y(ui_Register, 158);
    lv_obj_set_align(ui_Register, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Register, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Register, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Register, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Register, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RegisterLabel = lv_label_create(ui_Register);
    lv_obj_set_width(ui_RegisterLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RegisterLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RegisterLabel, -8);
    lv_obj_set_y(ui_RegisterLabel, 0);
    lv_obj_set_align(ui_RegisterLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RegisterLabel, "Register");

    ui_Raccount = lv_textarea_create(ui_RTab);
    lv_obj_set_width(ui_Raccount, 334);
    lv_obj_set_height(ui_Raccount, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Raccount, 3);
    lv_obj_set_y(ui_Raccount, -135);
    lv_obj_set_align(ui_Raccount, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Raccount, "Please enter your acoount number");
    lv_textarea_set_one_line(ui_Raccount, true);

    ui_Rpassword = lv_textarea_create(ui_RTab);
    lv_obj_set_width(ui_Rpassword, 336);
    lv_obj_set_height(ui_Rpassword, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Rpassword, 4);
    lv_obj_set_y(ui_Rpassword, -35);
    lv_obj_set_align(ui_Rpassword, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Rpassword, "Please enter your password");
    lv_textarea_set_one_line(ui_Rpassword, true);
    lv_textarea_set_password_mode(ui_Rpassword, true);

    ui_RpeatePassword = lv_textarea_create(ui_RTab);
    lv_obj_set_width(ui_RpeatePassword, 341);
    lv_obj_set_height(ui_RpeatePassword, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_RpeatePassword, 1);
    lv_obj_set_y(ui_RpeatePassword, 63);
    lv_obj_set_align(ui_RpeatePassword, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_RpeatePassword, "Please enter again your password");
    lv_textarea_set_one_line(ui_RpeatePassword, true);
    lv_textarea_set_password_mode(ui_RpeatePassword, true);

    ui_LTab = lv_tabview_add_tab(ui_TabView1, "Login");

    ui_accountText = lv_textarea_create(ui_LTab);
    lv_obj_set_width(ui_accountText, 248);
    lv_obj_set_height(ui_accountText, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_accountText, 6);
    lv_obj_set_y(ui_accountText, -96);
    lv_obj_set_align(ui_accountText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_accountText, "Enter You Account");
    lv_textarea_set_one_line(ui_accountText, true);

    ui_paswdtext = lv_textarea_create(ui_LTab);
    lv_obj_set_width(ui_paswdtext, 254);
    lv_obj_set_height(ui_paswdtext, 44);
    lv_obj_set_x(ui_paswdtext, 10);
    lv_obj_set_y(ui_paswdtext, 7);
    lv_obj_set_align(ui_paswdtext, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_paswdtext, "Enter You Password");
    lv_textarea_set_password_mode(ui_paswdtext, true);

    ui_Login = lv_btn_create(ui_LTab);
    lv_obj_set_width(ui_Login, 216);
    lv_obj_set_height(ui_Login, 50);
    lv_obj_set_x(ui_Login, 0);
    lv_obj_set_y(ui_Login, 120);
    lv_obj_set_align(ui_Login, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Login, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Login, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Login, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Login, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Loginabel = lv_label_create(ui_Login);
    lv_obj_set_width(ui_Loginabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Loginabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Loginabel, 1);
    lv_obj_set_y(ui_Loginabel, 0);
    lv_obj_set_align(ui_Loginabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Loginabel, "Login");

    ui_WelcomeLabel = lv_label_create(ui_pdText);
    lv_obj_set_width(ui_WelcomeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WelcomeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WelcomeLabel, -3);
    lv_obj_set_y(ui_WelcomeLabel, -251);
    lv_obj_set_align(ui_WelcomeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WelcomeLabel, "Create an Account or login");
    lv_obj_set_style_text_font(ui_WelcomeLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoginKeyboard = lv_keyboard_create(ui_LoginPage);
    lv_obj_set_width(ui_LoginKeyboard, 838);
    lv_obj_set_height(ui_LoginKeyboard, 268);
    lv_obj_set_x(ui_LoginKeyboard, 4);
    lv_obj_set_y(ui_LoginKeyboard, 149);
    lv_obj_set_align(ui_LoginKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LoginKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_loginmessPanel = lv_obj_create(ui_LoginPage);
    lv_obj_set_width(ui_loginmessPanel, 226);
    lv_obj_set_height(ui_loginmessPanel, 86);
    lv_obj_set_x(ui_loginmessPanel, 21);
    lv_obj_set_y(ui_loginmessPanel, 21);
    lv_obj_set_align(ui_loginmessPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loginmessPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_loginmessPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loginmessLabel = lv_label_create(ui_loginmessPanel);
    lv_obj_set_width(ui_loginmessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loginmessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_loginmessLabel, 0);
    lv_obj_set_y(ui_loginmessLabel, -1);
    lv_obj_set_align(ui_loginmessLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_loginmessLabel, "Register sucessfully");
    lv_obj_set_style_text_font(ui_loginmessLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Raccount, ui_event_Raccount, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Rpassword, ui_event_Rpassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RpeatePassword, ui_event_RpeatePassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_accountText, ui_event_accountText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_paswdtext, ui_event_paswdtext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LoginKeyboard, ui_event_LoginKeyboard, LV_EVENT_ALL, NULL);

}

void ui_LoginPage_screen_destroy(void)
{
    if(ui_LoginPage) lv_obj_del(ui_LoginPage);

    // NULL screen variables
    ui_LoginPage = NULL;
    ui_pdText = NULL;
    ui_TabView1 = NULL;
    ui_RTab = NULL;
    ui_Register = NULL;
    ui_RegisterLabel = NULL;
    ui_Raccount = NULL;
    ui_Rpassword = NULL;
    ui_RpeatePassword = NULL;
    ui_LTab = NULL;
    ui_accountText = NULL;
    ui_paswdtext = NULL;
    ui_Login = NULL;
    ui_Loginabel = NULL;
    ui_WelcomeLabel = NULL;
    ui_LoginKeyboard = NULL;
    ui_loginmessPanel = NULL;
    ui_loginmessLabel = NULL;

}
