// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAINPAGE_H
#define UI_MAINPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainPage
extern void ui_MainPage_screen_init(void);
extern void ui_MainPage_screen_destroy(void);
extern lv_obj_t * ui_MainPage;
extern lv_obj_t * ui_MainBg;
extern void ui_event_drawBtn(lv_event_t * e);
extern lv_obj_t * ui_drawBtn;
extern void ui_event_FileFolderBtn(lv_event_t * e);
extern lv_obj_t * ui_FileFolderBtn;
extern void ui_event_SeetingBtn(lv_event_t * e);
extern lv_obj_t * ui_SeetingBtn;
extern lv_obj_t * ui_TimeContain;
extern lv_obj_t * ui_yearLabel;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_weekLabel;
extern lv_obj_t * ui_weatherImg;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

