// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_MainPage = NULL;
lv_obj_t * ui_MainBg = NULL;
lv_obj_t * ui_drawBtn = NULL;
lv_obj_t * ui_FileFolderBtn = NULL;
lv_obj_t * ui_SeetingBtn = NULL;
lv_obj_t * ui_TimeContain = NULL;
lv_obj_t * ui_yearLabel = NULL;
lv_obj_t * ui_TimeLabel = NULL;
lv_obj_t * ui_weekLabel = NULL;
lv_obj_t * ui_weatherImg = NULL;
// event funtions
void ui_event_drawBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DrawPage, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_DrawPage_screen_init);
    }
}

void ui_event_FileFolderBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FilePage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_FilePage_screen_init);
    }
}

void ui_event_SeetingBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingPage_screen_init);
    }
}

// build funtions

void ui_MainPage_screen_init(void)
{
    ui_MainPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainBg = lv_img_create(ui_MainPage);
    lv_img_set_src(ui_MainBg, &ui_img_main_bg_png);
    lv_obj_set_width(ui_MainBg, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_MainBg, LV_SIZE_CONTENT);    /// 600
    lv_obj_set_align(ui_MainBg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainBg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MainBg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_drawBtn = lv_obj_create(ui_MainPage);
    lv_obj_remove_style_all(ui_drawBtn);
    lv_obj_set_width(ui_drawBtn, 64);
    lv_obj_set_height(ui_drawBtn, 64);
    lv_obj_set_x(ui_drawBtn, -226);
    lv_obj_set_y(ui_drawBtn, 157);
    lv_obj_set_align(ui_drawBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_drawBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_drawBtn, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_drawBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_drawBtn, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_drawBtn, &ui_img_1755233558, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_drawBtn, 20, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_drawBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_drawBtn, 100, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_src(ui_drawBtn, &ui_img_1755233558, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_FileFolderBtn = lv_obj_create(ui_MainPage);
    lv_obj_remove_style_all(ui_FileFolderBtn);
    lv_obj_set_width(ui_FileFolderBtn, 64);
    lv_obj_set_height(ui_FileFolderBtn, 64);
    lv_obj_set_x(ui_FileFolderBtn, -3);
    lv_obj_set_y(ui_FileFolderBtn, 151);
    lv_obj_set_align(ui_FileFolderBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FileFolderBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FileFolderBtn, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FileFolderBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FileFolderBtn, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_FileFolderBtn, &ui_img_folder_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_FileFolderBtn, 20, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_FileFolderBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_FileFolderBtn, 100, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_src(ui_FileFolderBtn, &ui_img_folder_png, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_SeetingBtn = lv_obj_create(ui_MainPage);
    lv_obj_remove_style_all(ui_SeetingBtn);
    lv_obj_set_width(ui_SeetingBtn, 64);
    lv_obj_set_height(ui_SeetingBtn, 64);
    lv_obj_set_x(ui_SeetingBtn, 230);
    lv_obj_set_y(ui_SeetingBtn, 149);
    lv_obj_set_align(ui_SeetingBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SeetingBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SeetingBtn, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SeetingBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SeetingBtn, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SeetingBtn, &ui_img_159716462, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SeetingBtn, 20, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_SeetingBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SeetingBtn, 100, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_src(ui_SeetingBtn, &ui_img_159716462, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_TimeContain = lv_obj_create(ui_MainPage);
    lv_obj_remove_style_all(ui_TimeContain);
    lv_obj_set_width(ui_TimeContain, 321);
    lv_obj_set_height(ui_TimeContain, 97);
    lv_obj_set_x(ui_TimeContain, 15);
    lv_obj_set_y(ui_TimeContain, -191);
    lv_obj_set_align(ui_TimeContain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimeContain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TimeContain, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TimeContain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeContain, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yearLabel = lv_label_create(ui_TimeContain);
    lv_obj_set_width(ui_yearLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_yearLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_yearLabel, -35);
    lv_obj_set_y(ui_yearLabel, -21);
    lv_obj_set_align(ui_yearLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_yearLabel, "2026/03/21");
    lv_obj_set_style_text_color(ui_yearLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_yearLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_yearLabel, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel = lv_label_create(ui_TimeContain);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel, -74);
    lv_obj_set_y(ui_TimeLabel, 22);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "19:54");
    lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weekLabel = lv_label_create(ui_TimeContain);
    lv_obj_set_width(ui_weekLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weekLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weekLabel, 32);
    lv_obj_set_y(ui_weekLabel, 25);
    lv_obj_set_align(ui_weekLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weekLabel, "Thu");
    lv_obj_set_style_text_color(ui_weekLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weekLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weekLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherImg = lv_img_create(ui_TimeContain);
    lv_img_set_src(ui_weatherImg, &ui_img_1225357782);
    lv_obj_set_width(ui_weatherImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherImg, 108);
    lv_obj_set_y(ui_weatherImg, 2);
    lv_obj_set_align(ui_weatherImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weatherImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weatherImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_drawBtn, ui_event_drawBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FileFolderBtn, ui_event_FileFolderBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SeetingBtn, ui_event_SeetingBtn, LV_EVENT_ALL, NULL);

}

void ui_MainPage_screen_destroy(void)
{
    if(ui_MainPage) lv_obj_del(ui_MainPage);

    // NULL screen variables
    ui_MainPage = NULL;
    ui_MainBg = NULL;
    ui_drawBtn = NULL;
    ui_FileFolderBtn = NULL;
    ui_SeetingBtn = NULL;
    ui_TimeContain = NULL;
    ui_yearLabel = NULL;
    ui_TimeLabel = NULL;
    ui_weekLabel = NULL;
    ui_weatherImg = NULL;

}
