// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_SettingPage = NULL;
lv_obj_t * ui_SettingTabview = NULL;
lv_obj_t * ui_ChangePsdBtn = NULL;
lv_obj_t * ui_ChangeBGBtn = NULL;
lv_obj_t * ui_ChangeLightBtn = NULL;
lv_obj_t * ui_ExitLoginBtn = NULL;
lv_obj_t * ui_ShutDraw3 = NULL;
lv_obj_t * ui_ChangePsdKey = NULL;
lv_obj_t * ui_PsdChangePanel = NULL;
lv_obj_t * ui_currentUserlabel = NULL;
lv_obj_t * ui_PsdChange1 = NULL;
lv_obj_t * ui_PsdChange2 = NULL;
lv_obj_t * ui_PsdChangeconfirmBtn = NULL;
lv_obj_t * ui_confirmlabel = NULL;
lv_obj_t * ui_warrningLabel = NULL;
lv_obj_t * ui_BGchangePanel = NULL;
lv_obj_t * ui_BGconfirmBtn = NULL;
lv_obj_t * ui_confirmlabel1 = NULL;
lv_obj_t * ui_BGroller = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_BgPreview = NULL;
lv_obj_t * ui_BrighrPanel = NULL;
lv_obj_t * ui_BrightnessBtn = NULL;
lv_obj_t * ui_Brightnesslabel = NULL;
lv_obj_t * ui_BrightSlider = NULL;
// event funtions
void ui_event_ShutDraw3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainPage_screen_init);
    }
}

void ui_event_ChangePsdKey(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_ChangePsdKey, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_PsdChange1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_ChangePsdKey,  ui_PsdChange1);
        lv_obj_move_foreground(ui_ChangePsdKey);
        _ui_flag_modify(ui_ChangePsdKey, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_PsdChange2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_ChangePsdKey,  ui_PsdChange2);
        lv_obj_move_foreground(ui_ChangePsdKey);
        _ui_flag_modify(ui_ChangePsdKey, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// build funtions

void ui_SettingPage_screen_init(void)
{
    ui_SettingPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingTabview = lv_tabview_create(ui_SettingPage, LV_DIR_TOP, 100);
    lv_obj_set_width(ui_SettingTabview, 1024);
    lv_obj_set_height(ui_SettingTabview, 600);
    lv_obj_set_x(ui_SettingTabview, 0);
    lv_obj_set_y(ui_SettingTabview, -4);
    lv_obj_set_align(ui_SettingTabview, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingTabview, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingTabview, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingTabview, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingTabview, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(lv_tabview_get_tab_btns(ui_SettingTabview), 50,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_SettingTabview), lv_color_hex(0xFFFFFF),
                                LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_SettingTabview), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_SettingTabview), lv_color_hex(0x5E5E5E),
                              LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_SettingTabview), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_SettingTabview), 0,  LV_PART_ITEMS | LV_STATE_CHECKED);

    ui_ChangePsdBtn = lv_tabview_add_tab(ui_SettingTabview, "Password");

    ui_ChangeBGBtn = lv_tabview_add_tab(ui_SettingTabview, "Backgound");

    ui_ChangeLightBtn = lv_tabview_add_tab(ui_SettingTabview, "Lightness");

    ui_ExitLoginBtn = lv_tabview_add_tab(ui_SettingTabview, "Exit");

    ui_ShutDraw3 = lv_btn_create(ui_SettingPage);
    lv_obj_set_width(ui_ShutDraw3, 47);
    lv_obj_set_height(ui_ShutDraw3, 50);
    lv_obj_set_x(ui_ShutDraw3, 477);
    lv_obj_set_y(ui_ShutDraw3, -161);
    lv_obj_set_align(ui_ShutDraw3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ShutDraw3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ShutDraw3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ShutDraw3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ShutDraw3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShutDraw3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ShutDraw3, &ui_img_1950574165, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ShutDraw3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ShutDraw3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ShutDraw3, lv_color_hex(0xD3CCCC), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ShutDraw3, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_ShutDraw3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_ShutDraw3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ChangePsdKey = lv_keyboard_create(ui_SettingPage);
    lv_obj_set_width(ui_ChangePsdKey, 753);
    lv_obj_set_height(ui_ChangePsdKey, 289);
    lv_obj_set_x(ui_ChangePsdKey, -4);
    lv_obj_set_y(ui_ChangePsdKey, 151);
    lv_obj_set_align(ui_ChangePsdKey, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChangePsdKey, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_PsdChangePanel = lv_obj_create(ui_SettingPage);
    lv_obj_set_width(ui_PsdChangePanel, 811);
    lv_obj_set_height(ui_PsdChangePanel, 433);
    lv_obj_set_x(ui_PsdChangePanel, 6);
    lv_obj_set_y(ui_PsdChangePanel, 36);
    lv_obj_set_align(ui_PsdChangePanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PsdChangePanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PsdChangePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PsdChangePanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentUserlabel = lv_label_create(ui_PsdChangePanel);
    lv_obj_set_width(ui_currentUserlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentUserlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentUserlabel, -15);
    lv_obj_set_y(ui_currentUserlabel, -154);
    lv_obj_set_align(ui_currentUserlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_currentUserlabel, "Current User: QWER");
    lv_obj_set_style_text_font(ui_currentUserlabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PsdChange1 = lv_textarea_create(ui_PsdChangePanel);
    lv_obj_set_width(ui_PsdChange1, 539);
    lv_obj_set_height(ui_PsdChange1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_PsdChange1, -3);
    lv_obj_set_y(ui_PsdChange1, -56);
    lv_obj_set_align(ui_PsdChange1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PsdChange1, "Enter new password.");
    lv_textarea_set_one_line(ui_PsdChange1, true);

    ui_PsdChange2 = lv_textarea_create(ui_PsdChangePanel);
    lv_obj_set_width(ui_PsdChange2, 539);
    lv_obj_set_height(ui_PsdChange2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_PsdChange2, -3);
    lv_obj_set_y(ui_PsdChange2, 23);
    lv_obj_set_align(ui_PsdChange2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PsdChange2, "Enter again password.");
    lv_textarea_set_one_line(ui_PsdChange2, true);

    ui_PsdChangeconfirmBtn = lv_btn_create(ui_PsdChangePanel);
    lv_obj_set_width(ui_PsdChangeconfirmBtn, 86);
    lv_obj_set_height(ui_PsdChangeconfirmBtn, 50);
    lv_obj_set_x(ui_PsdChangeconfirmBtn, -6);
    lv_obj_set_y(ui_PsdChangeconfirmBtn, 125);
    lv_obj_set_align(ui_PsdChangeconfirmBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PsdChangeconfirmBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PsdChangeconfirmBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PsdChangeconfirmBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PsdChangeconfirmBtn, lv_color_hex(0xC0C0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PsdChangeconfirmBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PsdChangeconfirmBtn, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PsdChangeconfirmBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_confirmlabel = lv_label_create(ui_PsdChangeconfirmBtn);
    lv_obj_set_width(ui_confirmlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confirmlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_confirmlabel, -1);
    lv_obj_set_y(ui_confirmlabel, 2);
    lv_obj_set_align(ui_confirmlabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_confirmlabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_confirmlabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_confirmlabel, "confirm");
    lv_obj_set_style_text_color(ui_confirmlabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confirmlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_warrningLabel = lv_label_create(ui_PsdChangePanel);
    lv_obj_set_width(ui_warrningLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_warrningLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_warrningLabel, -245);
    lv_obj_set_y(ui_warrningLabel, 90);
    lv_obj_set_align(ui_warrningLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_warrningLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_warrningLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_text_color(ui_warrningLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_warrningLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BGchangePanel = lv_obj_create(ui_SettingPage);
    lv_obj_set_width(ui_BGchangePanel, 811);
    lv_obj_set_height(ui_BGchangePanel, 433);
    lv_obj_set_x(ui_BGchangePanel, 6);
    lv_obj_set_y(ui_BGchangePanel, 36);
    lv_obj_set_align(ui_BGchangePanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BGchangePanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_BGchangePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BGchangePanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BGconfirmBtn = lv_btn_create(ui_BGchangePanel);
    lv_obj_set_width(ui_BGconfirmBtn, 86);
    lv_obj_set_height(ui_BGconfirmBtn, 50);
    lv_obj_set_x(ui_BGconfirmBtn, 327);
    lv_obj_set_y(ui_BGconfirmBtn, 146);
    lv_obj_set_align(ui_BGconfirmBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BGconfirmBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BGconfirmBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BGconfirmBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BGconfirmBtn, lv_color_hex(0xC0C0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BGconfirmBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BGconfirmBtn, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BGconfirmBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_confirmlabel1 = lv_label_create(ui_BGconfirmBtn);
    lv_obj_set_width(ui_confirmlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confirmlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_confirmlabel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_confirmlabel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_confirmlabel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_confirmlabel1, "confirm");
    lv_obj_set_style_text_color(ui_confirmlabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confirmlabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BGroller = lv_roller_create(ui_BGchangePanel);
    lv_roller_set_options(ui_BGroller, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_BGroller, 100);
    lv_obj_set_width(ui_BGroller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_BGroller, 319);
    lv_obj_set_y(ui_BGroller, -21);
    lv_obj_set_align(ui_BGroller, LV_ALIGN_CENTER);

    ui_Panel1 = lv_obj_create(ui_BGchangePanel);
    lv_obj_set_width(ui_Panel1, 632);
    lv_obj_set_height(ui_Panel1, 304);
    lv_obj_set_x(ui_Panel1, -52);
    lv_obj_set_y(ui_Panel1, 29);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BgPreview = lv_img_create(ui_Panel1);
    lv_obj_set_width(ui_BgPreview, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BgPreview, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BgPreview, -2);
    lv_obj_set_y(ui_BgPreview, 6);
    lv_obj_set_align(ui_BgPreview, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BgPreview, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BgPreview, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BgPreview, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BgPreview, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrighrPanel = lv_obj_create(ui_SettingPage);
    lv_obj_set_width(ui_BrighrPanel, 811);
    lv_obj_set_height(ui_BrighrPanel, 433);
    lv_obj_set_x(ui_BrighrPanel, 6);
    lv_obj_set_y(ui_BrighrPanel, 36);
    lv_obj_set_align(ui_BrighrPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrighrPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_BrighrPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BrighrPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessBtn = lv_btn_create(ui_BrighrPanel);
    lv_obj_set_width(ui_BrightnessBtn, 86);
    lv_obj_set_height(ui_BrightnessBtn, 50);
    lv_obj_set_x(ui_BrightnessBtn, 327);
    lv_obj_set_y(ui_BrightnessBtn, 146);
    lv_obj_set_align(ui_BrightnessBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrightnessBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BrightnessBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BrightnessBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessBtn, lv_color_hex(0xC0C0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessBtn, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BrightnessBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Brightnesslabel = lv_label_create(ui_BrightnessBtn);
    lv_obj_set_width(ui_Brightnesslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Brightnesslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Brightnesslabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Brightnesslabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Brightnesslabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_Brightnesslabel, "confirm");
    lv_obj_set_style_text_color(ui_Brightnesslabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Brightnesslabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightSlider = lv_slider_create(ui_BrighrPanel);
    lv_slider_set_value(ui_BrightSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BrightSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BrightSlider, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_BrightSlider, 640);
    lv_obj_set_height(ui_BrightSlider, 70);
    lv_obj_set_x(ui_BrightSlider, 23);
    lv_obj_set_y(ui_BrightSlider, -9);
    lv_obj_set_align(ui_BrightSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BrightSlider, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrightSlider, lv_color_hex(0x5F5F5F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ShutDraw3, ui_event_ShutDraw3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ChangePsdKey, ui_event_ChangePsdKey, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PsdChange1, ui_event_PsdChange1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PsdChange2, ui_event_PsdChange2, LV_EVENT_ALL, NULL);

}

void ui_SettingPage_screen_destroy(void)
{
    if(ui_SettingPage) lv_obj_del(ui_SettingPage);

    // NULL screen variables
    ui_SettingPage = NULL;
    ui_SettingTabview = NULL;
    ui_ChangePsdBtn = NULL;
    ui_ChangeBGBtn = NULL;
    ui_ChangeLightBtn = NULL;
    ui_ExitLoginBtn = NULL;
    ui_ShutDraw3 = NULL;
    ui_ChangePsdKey = NULL;
    ui_PsdChangePanel = NULL;
    ui_currentUserlabel = NULL;
    ui_PsdChange1 = NULL;
    ui_PsdChange2 = NULL;
    ui_PsdChangeconfirmBtn = NULL;
    ui_confirmlabel = NULL;
    ui_warrningLabel = NULL;
    ui_BGchangePanel = NULL;
    ui_BGconfirmBtn = NULL;
    ui_confirmlabel1 = NULL;
    ui_BGroller = NULL;
    ui_Panel1 = NULL;
    ui_BgPreview = NULL;
    ui_BrighrPanel = NULL;
    ui_BrightnessBtn = NULL;
    ui_Brightnesslabel = NULL;
    ui_BrightSlider = NULL;

}
