// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SETTINGPAGE_H
#define UI_SETTINGPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingPage
extern void ui_SettingPage_screen_init(void);
extern void ui_SettingPage_screen_destroy(void);
extern lv_obj_t * ui_SettingPage;
extern lv_obj_t * ui_SettingTabview;
extern lv_obj_t * ui_ChangePsdBtn;
extern lv_obj_t * ui_ChangeBGBtn;
extern lv_obj_t * ui_ChangeLightBtn;
extern lv_obj_t * ui_ExitLoginBtn;
extern void ui_event_ShutDraw3(lv_event_t * e);
extern lv_obj_t * ui_ShutDraw3;
extern void ui_event_ChangePsdKey(lv_event_t * e);
extern lv_obj_t * ui_ChangePsdKey;
extern lv_obj_t * ui_PsdChangePanel;
extern lv_obj_t * ui_currentUserlabel;
extern void ui_event_PsdChange1(lv_event_t * e);
extern lv_obj_t * ui_PsdChange1;
extern void ui_event_PsdChange2(lv_event_t * e);
extern lv_obj_t * ui_PsdChange2;
extern lv_obj_t * ui_PsdChangeconfirmBtn;
extern lv_obj_t * ui_confirmlabel;
extern lv_obj_t * ui_warrningLabel;
extern lv_obj_t * ui_BGchangePanel;
extern lv_obj_t * ui_BGconfirmBtn;
extern lv_obj_t * ui_confirmlabel1;
extern lv_obj_t * ui_BGroller;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_BgPreview;
extern lv_obj_t * ui_BrighrPanel;
extern lv_obj_t * ui_BrightnessBtn;
extern lv_obj_t * ui_Brightnesslabel;
extern lv_obj_t * ui_BrightSlider;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

