SET(SOURCES components/ui_comp_button1.c
    components/ui_comp.c
    screens/ui_LoginPage.c
    screens/ui_MainPage.c
    screens/ui_DrawPage.c
    screens/ui_FilePage.c
    screens/ui_SettingPage.c
    ui.c
    components/ui_comp_hook.c
    ui_helpers.c
    images/ui_img_whitebtn_png.c
    images/ui_img_main_bg_png.c
    images/ui_img_1755233558.c
    images/ui_img_folder_png.c
    images/ui_img_159716462.c
    images/ui_img_1225357782.c
    images/ui_img_1716423352.c
    images/ui_img_1966341745.c
    images/ui_img_1313573954.c
    images/ui_img_1453421446.c
    images/ui_img_1028212308.c
    images/ui_img_578315105.c
    images/ui_img_929597880.c
    images/ui_img_895563273.c
    images/ui_img_28177221.c
    images/ui_img_1053551958.c
    images/ui_img_381824271.c
    images/ui_img_699904908.c
    images/ui_img_1950574165.c
    images/ui_img_canvas1_png.c
    images/ui_img_canvas2_png.c
    images/ui_img_canvas3_png.c
    images/ui_img_canvasbg1_png.c
    images/ui_img_canvasbg2_png.c
    images/ui_img_canvasbg3_png.c
    images/ui_img_1479983256.c
    images/ui_img_2132644374.c
    images/ui_img_1668448959.c
    images/ui_img_1279319559.c
    images/ui_img_258598861.c
    images/ui_img_1527121588.c
    images/ui_img_1073906465.c
    images/ui_img_299028513.c
    images/ui_img_537269857.c)

add_library(ui ${SOURCES})
