// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_LoginPage.h"
#include "screens/ui_MainPage.h"
#include "screens/ui_DrawPage.h"
#include "screens/ui_FilePage.h"
#include "screens/ui_SettingPage.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_whitebtn_png);    // assets/whitebtn.png
LV_IMG_DECLARE(ui_img_main_bg_png);    // assets/main_bg.png
LV_IMG_DECLARE(ui_img_1755233558);    // assets/customization-fill (1).png
LV_IMG_DECLARE(ui_img_folder_png);    // assets/folder.png
LV_IMG_DECLARE(ui_img_159716462);    // assets/settings-fill (1).png
LV_IMG_DECLARE(ui_img_1225357782);    // assets/大雨.png
LV_IMG_DECLARE(ui_img_1716423352);    // assets/铅笔.png
LV_IMG_DECLARE(ui_img_1966341745);    // assets/cursor-01.png
LV_IMG_DECLARE(ui_img_1313573954);    // assets/刷子.png
LV_IMG_DECLARE(ui_img_1453421446);    // assets/橡皮.png
LV_IMG_DECLARE(ui_img_1028212308);    // assets/颜料盘.png
LV_IMG_DECLARE(ui_img_578315105);    // assets/画布.png
LV_IMG_DECLARE(ui_img_929597880);    // assets/多边形2.png
LV_IMG_DECLARE(ui_img_895563273);    // assets/截图.png
LV_IMG_DECLARE(ui_img_28177221);    // assets/墨迹1.png
LV_IMG_DECLARE(ui_img_1053551958);    // assets/墨迹2.png
LV_IMG_DECLARE(ui_img_381824271);    // assets/墨迹3.png
LV_IMG_DECLARE(ui_img_699904908);    // assets/墨迹4.png
LV_IMG_DECLARE(ui_img_1950574165);    // assets/关闭.png
LV_IMG_DECLARE(ui_img_canvas1_png);    // assets/canvas1.png
LV_IMG_DECLARE(ui_img_canvas2_png);    // assets/canvas2.png
LV_IMG_DECLARE(ui_img_canvas3_png);    // assets/canvas3.png
LV_IMG_DECLARE(ui_img_canvasbg1_png);    // assets/CanvasBG1.png
LV_IMG_DECLARE(ui_img_canvasbg2_png);    // assets/CanvasBG2.png
LV_IMG_DECLARE(ui_img_canvasbg3_png);    // assets/CanvasBG3.png
LV_IMG_DECLARE(ui_img_1479983256);    // assets/直线.png
LV_IMG_DECLARE(ui_img_2132644374);    // assets/三角形.png
LV_IMG_DECLARE(ui_img_1668448959);    // assets/圆.png
LV_IMG_DECLARE(ui_img_1279319559);    // assets/长方形.png
LV_IMG_DECLARE(ui_img_258598861);    // assets/六边形.png
LV_IMG_DECLARE(ui_img_1527121588);    // assets/星.png
LV_IMG_DECLARE(ui_img_1073906465);    // assets/后退.png
LV_IMG_DECLARE(ui_img_299028513);    // assets/前进.png
LV_IMG_DECLARE(ui_img_537269857);    // assets/删除.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
